package com.clubfactory.gm.price.model.po;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CrmShopifyClusterPO {
    /**
     * ID
     * This field was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    private Long id;

    /**
     * 0 正常 -1 删除
     * This field was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    private Boolean isDeleted;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    private Date createTime;

    /**
     * 修改时间
     * This field was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * 站点
     * This field was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    private String site;

    /**
     * 聚类规则
     * This field was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    private String ruleContent;
}